### ISSUE TITLE
Change Repo-Name?

### ISSUE THREAD

**Issue by cagix** [Artificial-Intelligence-FHB-TDU/KI-Vorlesung#140]
Wir haben unsere Organisation "KI-Vorlesung" und das Vorlesungs-Repo "Lecture" genannt. Das passt auch eigentlich ganz gut. 

Aber mir ist kürzlich aufgefallen, wenn Studis sich das Repo forken, dass dann der Fork im Studi-Repo auch einfach nur "Lecture" heisst, was nicht besonders aussagekräftig ist. 

Mein Vorschlag ist, dass wir den Namen für das Lecture-Repo nochmal überdenken. Vielleicht "KI-Lecture" (bestes denglisch)? Und, damit es keine Doppelungen gibt, den Namen der Organisation anpassen: "KI @ FHB & TDU" (oder so ähnlich, falls das technisch geht).

@cyildiz @jposselt Was denkt Ihr?

---

Okay, ich halte mal als Ergebnis der Diskussion fest:

- [x] Repo: ~~"KI-Vorlesung" oder "KI-Lecture"~~ => **KI-Vorlesung** (deutschsprachiges Material)
- [x] Organisation:
    - [x] Display-Name: ~~"KI-Lecture @ FHB/TDU"~~ => **Artificial Intelligence @ FHB/TDU** (englischsprachiges "Portal")
    - [x] User-Name: ~~"KI-Lecture_FHB_TDU"~~ => **Artificial-Intelligence-FHB-TDU** (keine Unterstriche erlaubt)
- [x] `Readme.md`: Link zu den Contributors
- [x] `static/license.html`: Link zu den Contributors
- [x] `static/license.html`: Link auf das Repo
- [x] `config.yaml`: ~~Link auf die GH-~~ (nicht mehr vorhanden)
- [x] `config.yaml`: `editURL`
- [x] Zusätzlich noch einmal "grep" nach dem alten Repo-Namen
- [x] Zusätzlich noch einmal "grep" nach dem alten Organisations-Namen
- [x] Lokale Workingcopy: `git remote set-url origin <neuer pfad>`

---

Würde ich aber erst umsetzen, wenn wir hier, im Exams- und im Quizzes-Repo nicht mehr aktiv am Arbeiten sind, oder?

- [x] https://github.com/KI-Vorlesung/Lecture/issues/107
- [x] https://github.com/KI-Vorlesung/Exams/issues/4
- [x] https://github.com/KI-Vorlesung/Exams/pull/5
- [x] https://github.com/KI-Vorlesung/Exams/pull/6

**Comment by cyildiz** [comment]
KI-Lecture für Repo finde ich gut.

Den Organisationsnamen finde ich auch gut, wenn das so geht.
Alternativ könnte man KI_at_FHB_TDU oder nur KI_FHB_TDU verwenden?

Wenn von dem Organisationsnamen auch ersichtlich sein soll, dass es sich um eine Vorlesung handelt, wäre KI-Vorlesung_FHB_TDU eine Alternative?

**Comment by jposselt** [comment]
Wenn wir den Organisationsnamen ändern, können wir den Namen "KI-Vorlesung" auch für das Repo verwenden.

**Comment by cyildiz** [comment]
Dann könnte man für die Organisation 
"KI-Lecture_FHB_TDU"
verwenden (internationaler).

**Comment by cagix** [comment]
> Wenn wir den Organisationsnamen ändern, können wir den Namen "KI-Vorlesung" auch für das Repo verwenden.

finde ich charmant, bin aber am überlegen, ob die repo-namen besser in englisch bleiben sollten? also eher "ki-lecture", auch wenn das ganz böses denglisch ist. aber "ki-vorlesung" ist auch gut :)

**Comment by cagix** [comment]
> Dann könnte man für die Organisation
> "KI-Lecture_FHB_TDU"
> verwenden (internationaler).

oder "KI-Lecture @ FHB/TDU", also ohne Unterstriche?

**Comment by cyildiz** [comment]
> oder "KI-Lecture @ FHB/TDU", also ohne Unterstriche?

genau, wenn die Zeichen so verwendet werden dürfen...

**Comment by cagix** [comment]
> > oder "KI-Lecture @ FHB/TDU", also ohne Unterstriche?
> 
> genau, wenn die Zeichen so verwendet werden dürfen...

hab mir das grad angeschaut: wir haben einen "displayed" name, dort können vermutlich sonderzeichen rein. dazu gehört aber auch der "user name" der organisation, der dann bestandteil der url ist. da geht das ziemlich sicher nicht.

**Comment by cagix** [comment]
d.h. die Lösung wäre:
- Display-Name: "KI-Lecture @ FHB/TDU"
- User-Name: "KI-Lecture_FHB_TDU"

richtig?

wir müssen dann alle unsere lokalen clones aktualisieren (also einmal mit `git remote set-url origin <neue url>" die pfade aktualisieren).

**Comment by cagix** [comment]
Okay, ich halte mal als Ergebnis der Diskussion fest:

- [ ] Repo: "KI-Vorlesung" oder "KI-Lecture"
- [ ] Organisation:
    - [ ] Display-Name: "KI-Lecture @ FHB/TDU"
    - [ ] User-Name: "KI-Lecture_FHB_TDU"
- [ ] Anschließend müssen im `Readme.md` und `static/license.html` je der Link zu den Contributors plus der Link auf das Repo, und im `config.yaml` der Link auf die GH-Page sowie die `editURL` aktualisiert werden. Zusätzlich noch einmal "grep" nach dem alten Organisations- und nochmal dem alten Repo-Namen machen.
- [ ] Und jeder muss in seiner lokalen Workingcopy mit `git remote set-url origin <neuer pfad>` die Pfade aktualisieren.

---

Würde ich aber erst umsetzen, wenn wir hier, im Exams- und im Quizzes-Repo nicht mehr aktiv am Arbeiten sind, oder?

- [ ] https://github.com/KI-Vorlesung/Lecture/issues/131
- [ ] https://github.com/KI-Vorlesung/Lecture/issues/107
- [ ] https://github.com/KI-Vorlesung/Quizzes/issues/50
- [ ] https://github.com/KI-Vorlesung/Exams/issues/4
- [ ] https://github.com/KI-Vorlesung/Exams/pull/5
